install:
- ps: >-

    choco install gitversion.portable -pre -y
    
    $output = gitversion
    
    $joined = $output -join "`n"
    
    $versionInfo = $joined | ConvertFrom-Json
    
    $versionInfo | % { foreach ($property in $_.PSObject.Properties) { Set-AppveyorBuildVariable -Name "GitVersion_$($property.Name)" -Value "$($_.PSObject.properties[$property.Name].Value)"    }}
    
    $script_versionNumber = "$($versionInfo.NuGetVersionV2).build.$($env:APPVEYOR_BUILD_ID)"
    
    Update-AppveyorBuild -Version $script_versionNumber
pull_requests:
  do_not_increment_build_number: true
os: Default Azure
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-

    cd C:\projects\zendeskapi-v2\src

    nuget.exe restore
build:
  project: C:\projects\zendeskapi-v2\src\ZendeskApi_v2_vs2013.sln
  verbosity: minimal
test: on
test_script:
- ps: nunit3-console C:\projects\zendeskapi-v2\src\Tests\bin\Release\Tests.dll /framework:net-4.5
artifacts:
- path: '\src\ZendeskApi_v2_Package\*.nupkg'
  name: Pakage
before_deploy:
- ps: >-
    if($env:APPVEYOR_BUILD_VERSION.contains("-")) {
        $env:Is_Prerelease  = 'true'
    }else{

    $env:Is_Prerelease  = 'false'

    }
deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master
    Is_Prerelease: false
- provider: Environment
  name: PreRelease Nuget Feed
  on:
    branch: master
    Is_Prerelease: true