version: 3.0.{build}
os: Default Azure
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    cd C:\projects\zendeskapi-v2

    nuget.exe restore
build:
  verbosity: minimal
test_script:
- ps: nunit-console C:\projects\zendeskapi-v2\Tests\bin\Release\Tests.dll /framework:net-4.5
artifacts:
- path: '\ZendeskApi_v2_Package\*.nupkg'
  name: Pakage
deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master